name: CI

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install Yarn
        run: npm install --global yarn

      - name: Install Dependencies
        run: yarn

      - name: Run Tests
        run: yarn jest --coverage
